### ISSUE TITLE
Not showing up in doc

### ISSUE THREAD

**Issue by danielone** [lukas77me/sketch-comments#1]
hmmm.. i run initialize and add comment but Shape layer in initialize looks empty and add comment dialog comes up but nothing shows up?

using v 3.3.2

**Comment by danielone** [comment]
![image](https://cloud.githubusercontent.com/assets/3112043/7576524/66621910-f7f3-11e4-8917-94b27a806b9f.png)

**Comment by lukas77me** [comment]
Yes, you're right, the plugin seems to be broken at the moment with Sketch 3.3. I'll look into updating it soon. Thanks for letting me know.

**Comment by danielone** [comment]
Thanks Lukas! any eta ?

**Comment by lukas77me** [comment]
I'll try to update it this week.

**Comment by danielone** [comment]
Thanks Lukas!!


________________________________

**Comment by lukas77me** [comment]
Everything should work in the latest version of Sketch now.

**Comment by danielone** [comment]
thank you! downloading now!


?
________________________________
